# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    environment:
      VERSION: &version 0.1.10
      AWS_REGION: us-west-2
      MY_ENV: testing
    docker:
      - image: &image golang:latest

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/mschurenko/entrypoint
    steps:
      - checkout
      - run: mkdir ./workspace
      - run: go test -v .
      - run: go build -ldflags "-X main.version=$VERSION" -race -o entrypoint
      - run: cp -v ./entrypoint ./workspace

      - persist_to_workspace:
          root: workspace
          paths:
            - entrypoint
  test:
    docker:
      - image: docker:18.09.1-git
    working_directory: /go/src/github.com/mschurenko/entrypoint/testing
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ./artifacts
      - run: pwd
      - run: ls -l .
      - run: ls -l ./artifacts
      - run: docker info
      - run: docker build -t test -f testing/Dockerfile .
      - run: docker run -t test ls /

  publish-github-release:
    environment:
      VERSION: *version
    docker:
      - image: *image
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "publish github release"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n ${VERSION} -soft ${VERSION} ./artifacts/


workflows:
  version: 2
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish-github-release:
          filters:
            branches:
              only: master
          requires:
            - test
